### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by Mindgames** [nextgrid/dll-web-app#77]
Let's create a smoooth CI 

- [x] Configure Kubernetes to roll out new version when new master is created 
- [x] Add YAML configuration file 
- [x] Test

**Comment by Mindgames** [comment]
YALM
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dllglobal
  name: dllglobal
  namespace: default
spec:
  minReadySeconds: 60
  replicas: 3
  selector:
    matchLabels:
      app: dllglobal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dllglobal
    spec:
      containers:
        - image: gcr.io/nextgrid-254813/github.com/nextgrid/dll-web-app
          imagePullPolicy: IfNotPresent
          name: dll-web-app-sha256-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: dllglobal
  name: dllglobal-hpa-dtop
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dllglobal
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: dllglobal
  name: dllglobal-service
  namespace: default
spec:
  clusterIP: 10.89.0.131
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31598
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: dllglobal
  sessionAffinity: None
  type: LoadBalancer
```
